### ISSUE TITLE
[Solved][Pinned] ModuleNotFoundError: No module named 'cts'

### ISSUE THREAD

**Issue by fuyuyuputao** [GestaltCogTeam/STEP#17]
Hi, it's a very nice work. But when I trying run this code, I find an error:
![QF)5QA61%SQ(L~IULCYEK%2](https://user-images.githubusercontent.com/79823933/196423530-9c0e8009-c498-48e7-be0e-87030844bf99.png)
When running `prediction_rescaled = SCALER_REGISTRY.get(self.scaler["func"])(forward_return[0], **self.scaler["args"])`

![USG)LKIHG5B C1KKS{)($K5](https://user-images.githubusercontent.com/79823933/196424071-6fbdebde-a16f-47e2-8062-8d8bb100b53c.png)
Maybe some codes missed, `SCALER_REGISTRY.get(self.scaler["func"])()` should be a function, but it wasn't defined
Best wishes
Thank you

**Comment by zezhishao** [comment]
Sorry, I can't reproduce your error. The latest code seems to work well. I'm guessing it might be caused by some additional modifications. Do you have more information about your changes?

**Comment by fuyuyuputao** [comment]
Hi, because of relative path, the raw codes can not  running. So I changed some relative path:

![$_4)D)DH@97OR1Q%3W2GC 8](https://user-images.githubusercontent.com/79823933/196581687-1ee1264d-1264-4aa6-b93a-758502a63f99.png)
The raw code is `+1` and I changed it to `-8`
If I remain `+1`, it will print an error:
![H`@KJHLW~R7L U_N5Z`R_7Y](https://user-images.githubusercontent.com/79823933/196582106-6a7de4a3-23a5-41d1-8925-776dd720f488.png)
![E5XQ 3N(}AMQD9%00~P@432](https://user-images.githubusercontent.com/79823933/196582119-c38eed34-e645-4b26-84fd-80b5a55291a3.png)

`SCALER_REGISTRY.get(self.scaler["func"])()` seem to be a re-scale function, I would appreciate if you tell me this function's abs path/full name.
Thank you very much
best wishes

**Comment by zezhishao** [comment]
The re-scale function is `re_standard_transform` in `basicts/data/transform.py`.

**Comment by zezhishao** [comment]
I've tested STEP on a Windows PC and the code seems to work fine as well.
Please make sure you follow the instructions in the README.

**Comment by fuyuyuputao** [comment]
Hi, I have tried running the raw codes in ubuntu, but I found the same error as windows10. I changed `SCALER_REGISTRY.get(self.scaler["func"])()` to transform.re_standard_transform by used an abs path. Fortunately，I have solved this error. Maybe, this error is caused by my device. 
Thank you very much
Best wishes

**Comment by zezhishao** [comment]
You're welcome, and if you have any questions, please feel free to create a new issue.

**Comment by catcatwang** [comment]
> Hi, I have tried running the raw codes in ubuntu, but I found the same error as windows10. I changed `SCALER_REGISTRY.get(self.scaler["func"])()` to transform.re_standard_transform by used an abs path. Fortunately，I have solved this error. Maybe, this error is caused by my device. Thank you very much Best wishes

Hi, why do I change 'SCALER_REGISTRY.get(self.scaler["func"])()' to transform.re_standard_transform and still report an error? The error is 'ModuleNotFoundError: No module named 'cts'. '

**Comment by fuyuyuputao** [comment]
> > Hi, I have tried running the raw codes in ubuntu, but I found the same error as windows10. I changed `SCALER_REGISTRY.get(self.scaler["func"])()` to transform.re_standard_transform by used an abs path. Fortunately，I have solved this error. Maybe, this error is caused by my device. Thank you very much Best wishes
> 
> Hi, why do I change 'SCALER_REGISTRY.get(self.scaler["func"])()' to transform.re_standard_transform and still report an error? The error is 'ModuleNotFoundError: No module named 'cts'. '

![image](https://user-images.githubusercontent.com/79823933/196840429-ea2d1cd9-583b-4da5-9e80-49b9fdfd3b4e.png)
Firstly, maybe you shoule change `+1` to `*` so as to suit your path. 
Best wishes

**Comment by catcatwang** [comment]
> > > 嗨，我试过在ubuntu中运行原始代码，但我发现和windows10一样的错误。`SCALER_REGISTRY.get(self.scaler["func"])()`我通过使用 abs 路径更改为 transform.re_standard_transform。幸运的是，我已经解决了这个错误。也许，这个错误是由我的设备引起的。非常感谢你 最良好的祝愿
> > 
> > 
> > 你好，为什么我把'SCALER_REGISTRY.get(self.scaler["func"])()'改成transform.re_standard_transform还是报错？错误是“ModuleNotFoundError：没有名为“cts”的模块。'
> 
> ![图片](https://user-images.githubusercontent.com/79823933/196840429-ea2d1cd9-583b-4da5-9e80-49b9fdfd3b4e.png) 首先，也许你应该改变`+1`以`*`适应你的道路。 最好的祝愿

Hi, sorry to bother you, but my code is indeed +1, but it's still an error.

**Comment by zezhishao** [comment]
This is weird...I can't reproduce this error in any way...
Could you provide more information about your environment?
Are you also running STEP on a Windows PC, and what is your python version?
In addition, have you tried running STEP from a Windows terminal or VSCode? (to avoid the influence of Pycharm)

**Comment by fuyuyuputao** [comment]
You can try to change +1 to any integer so as to the changed integer can be suitd for your path.This eroor is caused by relative path

**Comment by fuyuyuputao** [comment]
Maybe you can use the code that you uploaded to github  to try running again in another device.

**Comment by zezhishao** [comment]
Actually, I have already done this. @fuyuyuputao 

> I've tested STEP on a Windows PC and the code seems to work fine as well. Please make sure you follow the instructions in the README.

By the way, are you also using PyCharm?

**Comment by zezhishao** [comment]
By the way, are you also using PyCharm? @wangzhengzhengkai

**Comment by catcatwang** [comment]
> 顺便问一下，你也在使用 PyCharm 吗？@wangzhengzhengkai

Yes, I am using pycharm software and I changed +1 to another integer, still error.

**Comment by zezhishao** [comment]
OK, this seems to be caused by PyCharm.
I will figure it out.
You can run the code based on Windows Terminal or VSCode.
Please make sure to run the commands in the README in the directory `C:\path\to\STEP`, not `C:\path\to\STEP\step`.

**Comment by zezhishao** [comment]
OK, this seems to be caused by PyCharm.
I will figure it out.
You can run the code based on Windows Terminal or VSCode.
Please make sure to run the commands in the README in the directory `C:\path\to\STEP`, instead of `C:\path\to\STEP\step`.

**Comment by zezhishao** [comment]
When you are running the command under the directory `C:\path\to\STEP\step`, you will get the exact error in this issue.

**Comment by zezhishao** [comment]
This problem is indeed caused by PyCharm.
You can solve it by setting `/path/to/STEP`(`C:\path\to\STEP` on Windows) as your working directory, instead of `/path/to/STEP/step`.

(Do not forget to reverse the modification you have done.)

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/33691477/196853567-61db8974-d035-48f5-9fbc-653af11af386.png">

This is because PyCharm automatically recognizes `/path/to/STEP/step` as your working directory when the first time you run `/path/to/STEP/step/run.py`.

By the way, I would recommend Visual Studio Code if you do not know the many configurations in PyCharm. 
It's closer to a native terminal and less prone to problems.
