### ISSUE TITLE
关于 Pre-training Stage 和 Forecasting Stage 中 数据集的一些疑问？

### ISSUE THREAD

**Issue by ZhangYuan1998** [GestaltCogTeam/STEP#2]
作者您好！很感谢您开源了自己的代码以及对此领域做出的贡献。

针对您的工作，有一些疑惑：
Pre-training Stage和Forecasting Stage在进行训练时是否采用的是同一个数据集，比如都采用PEMS04，只是说Pre-training Stage采用的是PEMS04中的长序列数据，Forecasting Stage采用是PEMS04的短序列数据（12个时间步）。

如果是的话，在Pre-training Stage中如何做到不会泄漏Forecasting Stage需要预测的数据？因为文章中采用的数据集都是按照错位滑动获取的。例如1-12时间步的数据预测结果是13-24，2-13的时间步的数据预测结果是14-25，以此类推。 如果作者使用长训练数据，假设使用为1-2016时间步的连续数据进行Pre-training，然后利用这些数据生成的隐藏特征H在输入至GWN，此时假设GWN输入的短序列数据为1-12，那么将预测13-24，然而实际上13-24在Pre-training Stage已经看到了。在此有些疑惑，这样会不会就导致了标签泄漏？

期待您的回复！

**Comment by zezhishao** [comment]
感谢您的关注。
由滑动窗口获取到的样本数据会被分成训练、测试、验证，而预训练阶段和预测阶段遵循统一的数据划分。
也就是说，TSFormer只用训练集数据进行预训练。因此我觉得应该是没有数据泄露的问题的。
不知道是否解答了您的疑问，欢迎随时交流。

**Comment by ZhangYuan1998** [comment]
感谢您的回复！问题已经得到解决！非常感谢！

**Comment by zezhishao** [comment]
好的，欢迎随时交流～
