### ISSUE TITLE
What does the section 4 mean in the readme.md?

### ISSUE THREAD

**Issue by addicter2017** [GestaltCogTeam/STEP#21]
Hi!

In the _Forecasting Stage_ of readme.md, you said "Then trian the downstream STGNN (Graph WaveNet) like in section 4". I tried to find that in your paper _Pre-training Enhanced Spatial-temporal Graph Neural Network for Multivariate Time Series Forecasting_, but it seems that the section 4 of the paper does not give the exact method on how to  continue this step. Could you please give some instructions on how to preceed? Thanks!

Yours,
Can

**Comment by zezhishao** [comment]
Hi, thanks for your interest, and sorry for misleading you as I didn't clean up the readme thoroughly.
"Section 4" means the "Train STEP based on a Pre-trained TSFormer" section in the readme.

**Comment by zezhishao** [comment]
Now I have updated the README file.

**Comment by addicter2017** [comment]
Thanks a lot!
