### ISSUE TITLE
想知道TSFormer提取长时间序列的效果

### ISSUE THREAD

**Issue by Azusa-Yuan** [GestaltCogTeam/STEP#22]
TSFormer提取的是长时间特征，但是下游任务是交通时空序列而不是时间序列任务。大佬在做实验的时候有对比其它时间序列模型的效果吗？或者当下游任务是时间序列时，能否有效提升效果。

**Comment by zezhishao** [comment]
我其实没太懂，交通预测也是时间序列预测任务的一种，您说的”不是时间序列任务“指的是？

**Comment by Azusa-Yuan** [comment]
> 

抱歉，我刚刚描述的不够准确，应该说的是只有时间维度的序列任务long sequence time-series forecasting (LSTF)。因为TSFFormer只提取了时间特征，所以我比较好奇下游任务是一个只有时间维度的序列任务时，能否有效提升效果

**Comment by zezhishao** [comment]
抱歉，这个我也没有测试过。
之后我或许我会测试一下，目前我正在BasicTS中加入LSTF常用的一些数据集。

**Comment by Azusa-Yuan** [comment]
> 抱歉，这个我也没有测试过。 之后我或许我会测试一下，目前我正在BasicTS中加入LSTF常用的一些数据集。

好的，谢谢
