### ISSUE TITLE
Hope to add visual part of the code

### ISSUE THREAD

**Issue by xiewenqiang666** [GestaltCogTeam/STEP#23]
Can you give the visual code of Figure 3？
BasicTS also does not provide the code of the prediction part, can this part be provided?

**Comment by zezhishao** [comment]
Thanks for your attention.
Unfortunately, the scripts of visualization are not tracked by git, and I also can not find these codes now.
You can plot Figure 3(a), (c), and (d) using the similarity metrics [here](https://github.com/zezhishao/STEP/blob/github/step/step_arch/similarity.py) based on seaborn and matplotlib.
And you can plot Figure 1(b) using the returns of [TSFormer](https://github.com/zezhishao/STEP/blob/ea2c3c3c3b735bc9ace5c7d0a5a27e12cd486cba/step/step_arch/tsformer/tsformer.py#L162) based on matplotlib.
These are not heavy works.

**Comment by xiewenqiang666** [comment]
Thank you very much for your patient guidance.

**Comment by zezhishao** [comment]
You're welcome and feel free to create a new issue if you have any questions.
