### ISSUE TITLE
在训练期间会同时使用CPU 和 GPU进行训练吗？

### ISSUE THREAD

**Issue by 1154761334** [GestaltCogTeam/STEP#27]
![image](https://user-images.githubusercontent.com/17095886/206127462-639ecbf9-dc95-4b86-93a2-a5c6c3c6c8ac.png)
<img width="2047" alt="image" src="https://user-images.githubusercontent.com/17095886/206127437-278d540a-eb94-412b-ad26-2256a71ad16a.png">

我在使用提供的代码时发现CPU 和GPU都busy，想咨询下是否同时使用GPU 和GPU一起训练，是为了最大限度利用资源吗？

**Comment by zezhishao** [comment]
训练过程仅仅在GPU上进行。STEP在预测阶段需要的计算量是较大的，不建议使用个人工作站级别的显卡做训练（3060Ti会比较慢）。我用的是两张V100或者两张3090。

**Comment by 1154761334** [comment]
老哥很感谢你的建议，目前我手头仅有的就是这块3060ti，本来计划想是买一块3090提升一下，但是考虑到最近价格上涨还是没买。转而从咸鱼上900一张买了两个p40。
1.打算通过两张p40先解决大显存有无问题。这样一些验证性的测试比如通过小的batch size 和 少量迭代数量可以先在我本地的环境上运行。
2.如果在少量迭代和 小的batch size下能有一个不错的效果，打算是租网上的显卡，也许几十块钱一个小时的云算力。如果后期能够做出一些成果也许能申请一台设备专门使用。
目前关于设备方面是这样一个计划。

**Comment by zezhishao** [comment]
好的。
