### ISSUE TITLE
您好，十分感谢您的工作，但是我遇到一个问题

### ISSUE THREAD

**Issue by stanli124** [GestaltCogTeam/STEP#28]
![image](https://user-images.githubusercontent.com/33780087/208104771-cbc221f1-dd2e-464e-9c29-46a1474454b8.png)
图中有8块gpu从头训练TSFormer，但是从日志里面看初始化好模型之后就没有后续的训练过程，日志也没有报错，gpu也显示占用着内存在运行，请问下这是什么情况，烦请解答，感谢！

**Comment by zezhishao** [comment]
抱歉，我没有遇到过这个问题，您对代码有什么修改吗？

**Comment by stanli124** [comment]
![image](https://user-images.githubusercontent.com/33780087/208106990-496c730c-e7df-4481-b835-a2bf9c3b3447.png)
![image](https://user-images.githubusercontent.com/33780087/208107072-c1abf875-e863-4021-ad76-43b732d26a4e.png)
我只修改了图片中的两个地方，第一个是传入的函数参数名错误了，第二个是要修改和服务器gpu的数量一致，不然会报错。
就这两个地方，其他没有修改

**Comment by zezhishao** [comment]
按道理应该没有问题，我无法复现这个问题，难以提供实质的帮助。建议您从以下两个方面排查：
1 重新严格地按照STEP的readme安装依赖，推荐使用conda创建一个新环境。
2 debug一下看看程序是在哪里终止的。

**Comment by stanli124** [comment]
感谢！我再试试，程序没有终止，只是卡在了图片中的位置一直没有继续运行

**Comment by stanli124** [comment]
感谢作者，我解决了。重新装了环境，然后可能是easy-torch对多gpu的支持有问题，我改成一个gpu跑就能整正常训练了

**Comment by zezhishao** [comment]
> 感谢！我再试试，程序没有终止，只是卡在了图片中的位置一直没有继续运行

如果您是通过后台的显存占用来判断程序是否还在运行的话，可能会有问题。
多卡运行的时候，程序意外退出，可能会在0卡以外的其他卡仍然保留未被释放的显存。但实际上程序已经停止了。

**Comment by zezhishao** [comment]
> 感谢作者，我解决了。重新装了环境，然后可能是easy-torch对多gpu的支持有问题，我改成一个gpu跑就能整正常训练了

easytorch对多卡的支持还可以啊，平时我也是用多卡跑，而且我在很多个多卡的机器上都测试过。

建议您还是debug一下看看问题出在哪里。最好还是在多卡加持下训练STEP，比较快～

**Comment by stanli124** [comment]
> 
谢谢，我后面debug看一下 ╰(*°▽°*)╯
