### ISSUE TITLE
The spectral patch encoder

### ISSUE THREAD

**Issue by zhyliu00** [GestaltCogTeam/STEP#3]
Hi! Thanks for the wonderful work and the open source code.

In the `Patch` class, each patch is Fourier transformed and then the output is fed into a linear layer to generate the patch embedding. I wonder the reason why conducting the Fourier transform first, which is not mentioned in the paper.

Thanks!

**Comment by zezhishao** [comment]
Hi, thank you for your interest!
Sorry for misleading you as I didn't clean up the code thoroughly.
**Fourier transform is not used in the code.** By all default, the parameter `spectral` in configuration files is set to false.

Performing the masked auto-encoding strategy in the frequency domain can slightly improve performance. The reason may be that the frequency domain is more resistant to random noise in time series.
However, such a performance gain has nothing to do with the motivation of STEP. I leave the Fourier transformation for my future work. So I neither introduce it in the paper nor execute it in the code.

**Comment by zhyliu00** [comment]
Thanks for the reply!
