### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by markNZed** [GestaltCogTeam/STEP#30]
Hi, could you please give me an idea of how long the transformer training takes? Thanks

**Comment by zezhishao** [comment]
Thank you for your attention. 
You can find my training logs in `training_logs/`.
Specifically, the TSFormer takes about 500 seconds/epoch on a single 3090 GPU.
On two 3090 GPUs, the whole STEP takes about 500 seconds/epoch.
You can use more GPUs by simply modifying `CFG.NUM_GPU` in the configuration file.

**Comment by markNZed** [comment]
That is great, thanks. I should have seen the training logs. I noticed one of them did not run through to completion:

https://github.com/zezhishao/STEP/blob/ea2c3c3c3b735bc9ace5c7d0a5a27e12cd486cba/training_logs/TSFormer_PEMS04.log#L960

Best wishes for your research.

**Comment by zezhishao** [comment]
Thanks for the reminder, this was manually interrupted by myself because I think the training epoch is enough at that point. However, training for a few more epochs should continue to improve performance.
