### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by wubo2180** [GestaltCogTeam/STEP#33]
您好，

非常感谢您的工作。请问这三个数据集METR-LA、PEMS-BAY和PEMS04的速度传感器之间的连接情况不会发生变化吧，也就是邻接矩阵不会随着时间推移而发生改变吧？

祝好

**Comment by zezhishao** [comment]
不会变化，预定义的图都是固定的。

**Comment by zezhishao** [comment]
是的，STEP目前学到的图是静态图。

**Comment by wubo2180** [comment]
请问这三个数据集METR-LA、PEMS-BAY和PEMS04的中的邻接矩阵文件`adj_mx.pkl`打开后，其值是介于[0,1]之间的，而不是0值（节点没有连接）或者1值（节点有连接）这种模式。请问`adj_mx.pkl`中的值代表是什么含义。

祝好！

**Comment by zezhishao** [comment]
具体含义可以参考论文DCRNN中对数据处理的介绍。
STEP中并未用到这几个邻接矩阵。

**Comment by LeeY0413** [comment]
你好 请问有PEMS03 04 07 08的adj_mx.pkl数据吗？能分享一下吗

**Comment by zezhishao** [comment]
参考BasicTS库的数据生成脚本即可生成。

**Comment by LeeY0413** [comment]
您好，那个脚本有点多。具体是哪一个，能分享一下代码吗？谢谢
