### ISSUE TITLE
如何在自己的数据集上训练模型

### ISSUE THREAD

**Issue by czy227** [GestaltCogTeam/STEP#36]
请问大神如何用自己制作数据集用STEP训练模型？

**Comment by zezhishao** [comment]
抱歉，我并不清楚你的数据集和数据特点，无法给你明确解答。

你可以考虑只用STEP的模型结构，将其放到你自己的pipeline中。STEP的模型结构在./step/step_arch/中，模型输入数据的含义可以参考[这里](https://github.com/zezhishao/STEP/blob/6703653ed876449a7666fe72b43626c0ddbadf6d/step/step_arch/step.py#L37)。

输入数据的形状中B代表batch size、L代表输入数据的长度、N代表变量的数量（例如传感器的数量）、3代表输入数据的维度，STEP中用到的数据中这3维分别是[传感器的测量值（交通速度或交通流量）、Time in Day特征、Day in Week特征]。
数据预处理过程可以参考[这里](https://github.com/zezhishao/STEP/blob/github/scripts/data_preparation/METR-LA/generate_training_data.py)。

**Comment by czy227** [comment]
非常开心您能这么快就回复我的问题！我是交通流量预测领域的初学者，感谢您能耐心解答我的问题。
我现在已经按照您github上的方法成功训练出了模型，但是它只能在您给定的数据集上监测模型的性能。如果我想在其他交通速度数据集上测试当前模型的性能，应该怎么做呢？
十分感激您的耐心解答！

**Comment by zezhishao** [comment]
具体的细节太多，您可以学习参考BasicTS中的数据集处理。METR-LA和PeMS-BAY、PeMS03、04、07、08都可以运行。
