### ISSUE TITLE
借鉴您的预训练模型

### ISSUE THREAD

**Issue by leirongzhen** [GestaltCogTeam/STEP#37]
大佬您好，我也想使用预训练的思想，用在生成对抗网络上，生成一段时间序列，请问您有甚麽好的建议吗？看您的代码，在预训练部分理解了，在后面的预测部分有点卡壳，之前没接触过GNN，代码没看懂，想听听您的意见。

**Comment by zezhishao** [comment]
抱歉，我没有什么想法。

**Comment by zezhishao** [comment]
抱歉，这个我不了解。

**Comment by leirongzhen** [comment]
谢谢您的回复，感谢您做的工作，对我还是有很大的启发，我下去继续研究一下，也希望能和您保持沟通。

**Comment by hawkiyc** [comment]
Hi, @leirongzhen.

For Generating Time Series Data with Generative Adversarial Network. You may try an architecture called WAVE-GAN. I have used this architecture to augment ECG signals. Please feel free to check my repository.

**Comment by leirongzhen** [comment]
> Hi, @leirongzhen.
> 
> For Generating Time Series Data with Generative Adversarial Network. You may try an architecture called WAVE-GAN. I have used this architecture to augment ECG signals. Please feel free to check my repository.


Thank you for your message, I paid attention to your repository, there may be questions to ask you later.
