### ISSUE TITLE
训练、测试过程的loss值可视化

### ISSUE THREAD

**Issue by czy227** [GestaltCogTeam/STEP#40]
作者您好！如果我想将模型的训练过程和测试过程的loss可视化（使用matplotlib等工具绘制二维折线图展现epochs-loss变化），应该在文档的那个地方添加可视化函数呢？没有找到mae、mape、rmse的计算位置。希望您能解答我的问题，谢谢！

**Comment by zezhishao** [comment]
您好，STEP是基于[BasicTS](https://github.com/zezhishao/BasicTS)开发的，[BasicTS](https://github.com/zezhishao/BasicTS)会自动产生和保存整个训练过程的log，以及**tensorboard**。你可以在`checkpoints`文件夹中找到生成的tensorbard。例如，`checkpoints/STEP_100/0ab1e5444a86dcaee6d80aa74ea8f3b9/tensorboard`。

如果您不打算使用tensorboard，想要直接操作损失函数，那么损失函数的实现可以在`basicts/runners/base_tsf_runner.py`中第207行`metric_forward`函数中找到。

**Comment by czy227** [comment]
感谢您这么及时的回复！我通过训练已经得到了checkpoints/STEP_100/0ab1e5444a86dcaee6d80aa74ea8f3b9/tensorboard函数，但是我想在训练完成的同时，绘制出纵坐标为mae、mape、rmse，横坐标为epochs的二维折线图，但是我找不到每个epoch计算mae、mape、rmse值的位置

**Comment by zezhishao** [comment]
`metric_forward`函数是所有metric function计算的入口，您可以debug进行修改。
另外，`checkpoints/STEP_100/0ab1e5444a86dcaee6d80aa74ea8f3b9`文件夹中的log文件同样记录着每一个epoch的训练、验证、测试的mae、mape、rmse。您也可以通过处理该文本文件实现您的目的。

**Comment by czy227** [comment]
明白您的像法了。十分感谢您的及时回复！
