### ISSUE TITLE
Question Regarding Self-loop Removal in Graph Structure Learning

### ISSUE THREAD

**Issue by fuyuyuputao** [GestaltCogTeam/STEP#42]
Hi！While reviewing your code, I noticed that you remove self-loops in the graph structure learning. I am curious about the rationale behind this decision, as I would like to deepen my understanding of the topic. Could you please help me understand why removing self-loops is important or beneficial in Graph Structure Learning?
Thank you for your time and consideration.
Best regards.

**Comment by zezhishao** [comment]
It will be added in downstream STGNNs. See https://github.com/zezhishao/STEP/blob/dd702eb686eb783caa4b12aa7aa1a63dc9ea0a77/step/step_arch/graphwavenet/model.py#L124.
