### ISSUE TITLE
关于pre-training结果的复现

### ISSUE THREAD

**Issue by HamLaertes** [GestaltCogTeam/STEP#48]
您好，我想请教您们关于pre-training的复现，我有以下的结果：

- [复现实验1] 我能使用您们提供的checkpoints以及代码、参数，复现downstream tasks的结果；

- [复现实验2] 我很难使用您们提供的代码与参数，复现pre-training的结果；以及用新pre-training的checkpoints复现downstream tasks的结果。

因为我能有效使用您们提供的checkpoints，所以pre-training的复现问题应该不来源于机器差异或者环境依赖差异；
所以，我想请教下关于pre-training的参数、代码，您们有细微的调整吗？或者引入一些其他的tricks帮助pre-training。

非常感谢！

**Comment by zezhishao** [comment]
根据您的描述我无法确定问题出在哪里，您可以提供更多的信息，尤其是对代码的修改。

**Comment by HamLaertes** [comment]
我没有对代码做任何的修改。。。所以我担心是预训练参数的差别。如果你们也没有对预训练参数做更多的调整，那么可能是机器的差异吧？

**Comment by zezhishao** [comment]
有点奇怪，我跑的代码和结果都在这个repo里面了，你也可以在training_logs看到我的结果。晚点我再跑一次试试吧。

**Comment by zezhishao** [comment]
您复现的结果是什么？不同的机器确实会有差异，但不会差很多才对。

**Comment by HamLaertes** [comment]
在我完全复现pre-training+graph wavenet finetuning的结果中，虽然比论文中低一点，但也是SOTA。。
只是pre-training中的过程中，validation和test的指标跟github中的logs差距比较大，我可以把logs发到你在论文中留的邮箱中，因为logs太长了在这里不好post。

**Comment by zezhishao** [comment]
按理来说，预训练阶段的Train和Valid应该是一样的。Test确实会和我的log里面不一样，因为我后面修复过一个bug。See issue #18 . 预训练阶段的Test没有啥意义，可以不用关注。只要Downstream中表现正常就行。
STEP曾重构过，重构之后的结果在training_logs文件夹中，可能会和论文中的值有偏差。
METR-LA和PEMS-BAY会更好一点，PEMS04可能会差一点。但应该都还是SOTA，不会影响文章结论。您可以引用repo中的值而不用论文中的值。

**Comment by HamLaertes** [comment]
我看了引用的issue，这确实解答了我的问题。您们的开源做的很好，感谢！
