### ISSUE TITLE
关于adj_mx.pkl这个数据集的问题

### ISSUE THREAD

**Issue by xzhoubinx** [GestaltCogTeam/STEP#49]
您好，我想请教一个问题，是就是 METR-LA 数据处理完成之后，会复制 adj_mx.pkl 到 datasets 目录。可是我发现把这个文件删了，也不影响后面的训练和推理测试，想问一下这个文件是不是没有什么意义的。这个是图数据么？后面的图学习模块不依赖这个数据集么？

**Comment by zezhishao** [comment]
是图数据，但STEP并不依赖先验图结构，它会自行学习。所以删掉这个文件对STEP是没有影响的，因为STEP没有使用它。
保留这个文件是因为本仓库是基于BasicTS库开发的，因此保留了BasicTS的数据预处理方法。BasicTS里面很多其他的Baselines是需要依赖图结构的。
