### ISSUE TITLE
关于预训练数据问题

### ISSUE THREAD

**Issue by researchgrunt** [GestaltCogTeam/STEP#5]
作者您好！很感谢您开源了自己的代码以及对此领域做出的贡献。

针对您的工作，有一些疑惑：
Pre-training Stage的数据是怎样生成的呢？我在您的代码里没有找到这部分内容，希望您能给予指导。

期待您的回复！

**Comment by zezhishao** [comment]
您好，预训练阶段和预测阶段使用同样的数据集划分形式。

**Comment by researchgrunt** [comment]
您好，非常感谢您的回复，但是我理解您在预训练阶段使用的是训练数据，不涉及训练集标签，但是预训练过程中计算MSE损失时，您计算的应该是训练集mask部分和原始训练集没有mask部分之间的损失，不知道我这样理解是否正确，我不知道您预训练阶段数据集是如何制作的，如果在您代码中有相应说明还请您指导，非常感谢！

**Comment by zezhishao** [comment]
一个时间序列的样本是通过一个滑动窗口从原始时间序列上取下来的，这个窗口一般有三个index。index[0]-index[1]一般是指historical data，index[1]-index[2]是指future data。
Pre-training stage和forecasting stage都遵循这样的数据使用形式，并且他们使用相同的数据集划分。
但是，在pre-training stage，由于我们使用Masked Auto Encoding策略，因此future data是没有使用的。Masked Auto Encoding策略会先在historical data上先mask，然后对masked部分进行重构，最后计算mask部分的重构损失，指导TSFormer的训练。另外，我们使用Mean Absolute Error作为损失函数。

代码可以参考dataloader/dataset.py和模型的forward函数。

不知这样的是否解答了您的疑问。

**Comment by researchgrunt** [comment]
非常感谢您细致的回复，我已经理解了您的讲解，也对您文章细节有了更多的了解，再次感谢您的回复和您开源的研究精神，期待有机会与您的合作，谢谢！

**Comment by zezhishao** [comment]
不客气～
