### ISSUE TITLE
多卡训练失败问题

### ISSUE THREAD

**Issue by stan-lei** [GestaltCogTeam/STEP#67]
您好，十分感谢您的工作，与issue #28 相同，我在使用的时候也遇到了多卡支持失败的问题，使用多卡训练时完全卡死在第一个epoch，但是切换使用单卡后可以正常运行，请问这可能是什么原因呢？

**Comment by stan-lei** [comment]
感觉应该是cuda版本的问题，easytorch在cuda12的情况下多卡训练会卡死，换成cuda11之后就正常了🥰

**Comment by zezhishao** [comment]
好的，感谢您的反馈，有时间我也测试一下。

**Comment by stan-lei** [comment]
收到，祝好。一鸣。
